# Generated by Django 5.2.11 on 2026-02-14 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_doctor_options_alter_vendor_options_and_more'),
        ('core', '0003_alter_pharmaceuticalcompany_options_and_more'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='voucher',
            options={'verbose_name': 'Voucher', 'verbose_name_plural': 'Vouchers'},
        ),
        migrations.AlterField(
            model_name='event',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pharmaceuticalcompany', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='doctors',
            field=models.ManyToManyField(blank=True, related_name='events', to='accounts.doctor', verbose_name='Doctors'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='event',
            name='voucher_expiry_days',
            field=models.IntegerField(default=90, verbose_name='Voucher Expiry Days'),
        ),
        migrations.AlterField(
            model_name='event',
            name='voucher_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Voucher Value'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Current Balance'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='accounts.doctor', verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='events.event', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='expiry_date',
            field=models.DateField(verbose_name='Expiry Date'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='initial_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Initial Value'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='issue_date',
            field=models.DateField(auto_now_add=True, verbose_name='Issue Date'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
