# Generated by Django 5.1.3 on 2026-02-24 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delegate_specialty_doctor_specialty_fk'),
        ('events', '0002_alter_event_options_alter_voucher_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='delegates',
            field=models.ManyToManyField(blank=True, related_name='events', to='accounts.delegate', verbose_name='Delegates'),
        ),
        migrations.AddField(
            model_name='event',
            name='specialties',
            field=models.ManyToManyField(blank=True, related_name='events', to='accounts.specialty', verbose_name='Specialties'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='events.event', verbose_name='Event'),
        ),
    ]
