# Generated by Django 5.2.11 on 2026-02-24 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_pharmaceuticalcompany_options_and_more'),
        ('events', '0003_event_delegates_event_specialties_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pharmaceuticalcompany', verbose_name='Company'),
        ),
    ]
