# Generated by Django 5.1.3 on 2026-03-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_voucher_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='event',
            name='payment_type',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CREDIT', 'Credit')], default='CREDIT', max_length=10, verbose_name='Payment Type'),
        ),
    ]
