# Generated by Django 5.1.3 on 2026-03-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_notes_event_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='payment_type',
            field=models.CharField(choices=[('CASH', 'Cash'), ('DEFERRED', 'Deferred')], default='DEFERRED', max_length=10, verbose_name='Payment Type'),
        ),
    ]
