# Generated by Django 5.2.11 on 2026-03-27 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
    ]
