# Generated by Django 5.2.11 on 2026-03-27 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_vendor_is_active'),
        ('events', '0007_voucher_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateTimeField(auto_now_add=True, verbose_name='Transfer Date')),
                ('from_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_made', to='accounts.doctor', verbose_name='From Doctor')),
                ('to_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_received', to='accounts.doctor', verbose_name='To Doctor')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='events.voucher', verbose_name='Voucher')),
            ],
            options={
                'verbose_name': 'Voucher Transfer',
                'verbose_name_plural': 'Voucher Transfers',
            },
        ),
    ]
