# Generated by Django 5.1.3 on 2026-02-12 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.voucher'),
        ),
        migrations.AddField(
            model_name='vendorsettlement',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.vendor'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.vendorsettlement'),
        ),
    ]
