# Generated by Django 5.2.11 on 2026-02-14 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_doctor_options_alter_vendor_options_and_more'),
        ('core', '0002_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pharmaceuticalcompany',
            options={'verbose_name': 'Pharmaceutical Company', 'verbose_name_plural': 'Pharmaceutical Companies'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterModelOptions(
            name='vendorsettlement',
            options={'verbose_name': 'Vendor Settlement', 'verbose_name_plural': 'Vendor Settlements'},
        ),
        migrations.AddField(
            model_name='vendorsettlement',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='pharmaceuticalcompany',
            name='address',
            field=models.TextField(verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='pharmaceuticalcompany',
            name='contact_person',
            field=models.CharField(max_length=255, verbose_name='Contact Person'),
        ),
        migrations.AlterField(
            model_name='pharmaceuticalcompany',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='pharmaceuticalcompany',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='pharmaceuticalcompany',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='pharmaceuticalcompany',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='pharmaceuticalcompany',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount_spent',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount Spent'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.doctor', verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='invoice_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Invoice Number'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='items_description',
            field=models.TextField(blank=True, verbose_name='Items Description'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='management_fee_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Management Fee Amount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='management_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=25.0, max_digits=5, verbose_name='Management Fee Percentage'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.vendorsettlement', verbose_name='Settlement'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total_deducted',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Deducted'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Transaction Date'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.vendor', verbose_name='Vendor'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.voucher', verbose_name='Voucher'),
        ),
        migrations.AlterField(
            model_name='vendorsettlement',
            name='amount_settled',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount Settled'),
        ),
        migrations.AlterField(
            model_name='vendorsettlement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='vendorsettlement',
            name='settlement_date',
            field=models.DateField(verbose_name='Settlement Date'),
        ),
        migrations.AlterField(
            model_name='vendorsettlement',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.vendor', verbose_name='Vendor'),
        ),
    ]
