# Generated by Django 5.2.11 on 2026-03-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_transactionotp'),
        ('events', '0006_alter_event_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='voucher',
        ),
        migrations.AddField(
            model_name='transaction',
            name='vouchers',
            field=models.ManyToManyField(related_name='transactions', to='events.voucher', verbose_name='Vouchers'),
        ),
        migrations.DeleteModel(
            name='TransactionOTP',
        ),
    ]
