"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os 
from django.utils.translation import gettext_lazy as _
from django.templatetags.static import static
from django.urls import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!tfp&zz+)^&_2g#fpkwnnrugvzaxz)1&%1qo4or%pqywoz@25o'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'unfold',   
    'modeltranslation',
    'import_export',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'settings',
    'reversation',
    'menu',
    'contact',
    'home',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
                'settings.context_processors.site_seo',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en'

LANGUAGES = [
    ('en', _('English')),
    ('ar', _('Arabic')),
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

UNFOLD = {
    "SHOW_LANGUAGES": True,
    "STYLES": [
        lambda request: static("admin/css/style.css"),
    ],
    "SCRIPTS": [
        lambda request: static("admin/js/rtl-fix.js"),
    ],
    "BORDER_RADIUS": "6px",
    "SITE_TITLE": "Restaurant Admin",
    "SITE_HEADER": "Restaurant Admin",
    "INDEX_TITLE": "Dashboard",

    "COLORS": {
        "base": {
            "50":  "rgb(248,250,252)",              # Slate 50
            "100": "rgb(241,245,249)",              # Slate 100
            "200": "rgb(226,232,240)",              # Slate 200
            "300": "rgb(203,213,225)",              # Slate 300
            "400": "rgb(148,163,184)",              # Slate 400
            "500": "rgb(100,116,139)",              # Slate 500
            "600": "rgb(71,85,105)",                # Slate 600
            "700": "rgb(51,65,85)",                 # Slate 700
            "800": "rgb(30,41,59)",                 # Slate 800
            "900": "rgb(15,23,42)",                 # Slate 900
            "950": "rgb(2,6,23)",                   # Slate 950
        },

        "primary": {
            "50":  "rgba(95,230,219,0.10)",
            "100": "rgba(95,230,219,0.20)",
            "200": "rgba(95,230,219,0.30)",
            "300": "rgba(95,230,219,0.45)",
            "400": "rgba(95,230,219,0.65)",
            "500": "rgb(95,230,219)",               # main color
            "600": "rgb(80,200,190)",
            "700": "rgb(65,170,160)",
            "800": "rgb(50,140,130)",
            "900": "rgb(35,110,100)",
            "950": "rgb(21,44,41)",
        },

        "font": {
            "subtle-light": "var(--color-base-300)",
            "subtle-dark": "var(--color-base-400)",

            "default-light": "var(--color-base-200)",
            "default-dark": "var(--color-base-300)",

            "important-light": "var(--color-base-50)",
            "important-dark": "var(--color-base-100)",
        },
    },
    "SHOW_VIEW_ON_SITE": True,
    "SHOW_HISTORY": True,
    "THEME": "dark", 
    
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": _("Dashboard"),
                "items": [
                    {
                        "title": _("Dashboard"),
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                ],
            },
            {
                "title": _("Menu Management"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Branches"),
                        "icon": "storefront",
                        "link": reverse_lazy("admin:menu_branch_changelist"),
                    },
                    {
                        "title": _("Categories"),
                        "icon": "category",
                        "link": reverse_lazy("admin:menu_mealcategory_changelist"),
                    },
                    {
                        "title": _("Meals"),
                        "icon": "restaurant_menu",
                        "link": reverse_lazy("admin:menu_meal_changelist"),
                    },
                ],
            },
            {
                "title": _("Orders"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Orders"),
                        "icon": "shopping_cart",
                        "link": reverse_lazy("admin:reversation_order_changelist"),
                    },
                ],
            },
            {
                "title": _("Reservations"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Staff Dashboard"),
                        "icon": "monitor_heart",
                        "link": reverse_lazy("reservation:staff_dashboard"),
                    },
                    {
                        "title": _("Reservations"),
                        "icon": "event_seat",
                        "link": reverse_lazy("admin:reversation_reservation_changelist"),
                    },
                    {
                        "title": _("Tables"),
                        "icon": "table_restaurant",
                        "link": reverse_lazy("admin:reversation_table_changelist"),
                    },
                    {
                        "title": _("Waiting List"),
                        "icon": "hourglass_empty",
                        "link": reverse_lazy("admin:reversation_waitinglist_changelist"),
                    },
                    {
                        "title": _("Time Slots"),
                        "icon": "schedule",
                        "link": reverse_lazy("admin:reversation_timeslot_changelist"),
                    },
                ],
            },
            {
                "title": _("Customer Messages"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Contacts"),
                        "icon": "mail",
                        "link": reverse_lazy("admin:contact_contact_changelist"),
                    },
                ],
            },
            {
                "title": _("Page Content"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Home Banner"),
                        "icon": "home",
                        "link": reverse_lazy("admin:settings_homebanner_changelist"),
                    },
                    {
                        "title": _("Home Story"),
                        "icon": "auto_stories",
                        "link": reverse_lazy("admin:settings_homeourstory_changelist"),
                    },
                    {
                        "title": _("About Banner"),
                        "icon": "info",
                        "link": reverse_lazy("admin:settings_aboutbanner_changelist"),
                    },
                    {
                        "title": _("About Story"),
                        "icon": "history_edu",
                        "link": reverse_lazy("admin:settings_aboutstory_changelist"),
                    },
                    {
                        "title": _("Intro Video"),
                        "icon": "play_circle",
                        "link": reverse_lazy("admin:settings_aboutintrovideo_changelist"),
                    },
                    {
                        "title": _("Why Us Items"),
                        "icon": "star",
                        "link": reverse_lazy("admin:settings_aboutwhyusitem_changelist"),
                    },
                    {
                        "title": _("Statistics"),
                        "icon": "analytics",
                        "link": reverse_lazy("admin:settings_aboutstat_changelist"),
                    },
                    {
                        "title": _("Services"),
                        "icon": "room_service",
                        "link": reverse_lazy("admin:settings_aboutservice_changelist"),
                    },
                    {
                        "title": _("Gallery"),
                        "icon": "photo_library",
                        "link": reverse_lazy("admin:settings_aboutgalleryimage_changelist"),
                    },
                ],
            },
            {
                "title": _("Site Settings"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("SEO Settings"),
                        "icon": "search",
                        "link": reverse_lazy("admin:settings_siteseosettings_changelist"),
                    },
                    {
                        "title": _("Theme Customization"),
                        "icon": "palette",
                        "link": reverse_lazy("admin:settings_themesettings_changelist"),
                    },
                    {
                        "title": _("Instagram Images"),
                        "icon": "photo_camera",
                        "link": reverse_lazy("admin:settings_instagramimage_changelist"),
                    },
                ],
            },
            {
                "title": _("System"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Users"),
                        "icon": "person",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                    {
                        "title": _("Groups"),
                        "icon": "group",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                ],
            },
        ],
    },
}
