# Generated by Django 5.1.3 on 2026-02-24 18:56

from django.db import migrations


def migrate_specialties(apps, schema_editor):
    Doctor = apps.get_model('accounts', 'Doctor')
    Specialty = apps.get_model('accounts', 'Specialty')
    
    for doctor in Doctor.objects.all():
        if doctor.specialty:
            specialty_obj, created = Specialty.objects.get_or_create(name=doctor.specialty)
            doctor.specialty_fk = specialty_obj
            doctor.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delegate_specialty_doctor_specialty_fk'),
    ]

    operations = [
        migrations.RunPython(migrate_specialties),
    ]
