# Generated by Django 5.2.11 on 2026-02-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_final_specialty_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Vendor Admin'), ('CASHIER', 'Vendor Cashier')], default='ADMIN', help_text='Vendor Admin has full access, Cashier can only process transactions via QR scan', max_length=20, verbose_name='Role'),
        ),
    ]
