# Generated by Django 5.1.3 on 2026-03-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='has_management_fee',
            field=models.BooleanField(default=True, verbose_name='Has Management Fee'),
        ),
    ]
