# Generated by Django 5.2.11 on 2026-03-27 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_doctor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='parent_vendor',
            field=models.ForeignKey(blank=True, help_text='If this is a cashier, specify the parent vendor it belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cashiers', to='accounts.vendor', verbose_name='Parent Vendor'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
