# Generated by Django 5.2.11 on 2026-03-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_vendor_parent_vendor_alter_doctor_email'),
        ('core', '0006_remove_transaction_voucher_transaction_vouchers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegate',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='delegates', to='core.pharmaceuticalcompany', verbose_name='Companies'),
        ),
        migrations.AddField(
            model_name='delegate',
            name='specialties',
            field=models.ManyToManyField(blank=True, related_name='delegates', to='accounts.specialty', verbose_name='Specialties'),
        ),
    ]
