"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-xdsfg(g@)offflh#gga$9kq0369i^&_2ox+4c+4xsl@&z=p18&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'unfold',  # Add Unfold before admin
    "unfold.contrib.filters",  # optional, if special filters are needed
    "unfold.contrib.forms",    # optional, if special forms are needed
    "unfold.contrib.inlines",  # optional, if special inlines are needed
    "unfold.contrib.import_export",  # optional, if django-import-export is used
    "unfold.contrib.guardian",  # optional, if django-guardian is used
    "unfold.contrib.simple_history",  # optional, if django-simple-history is used
    
    #'core.admin_config.HandramoutAdminConfig', # Replaces 'django.contrib.admin'
    'django.contrib.admin', # Restore default admin, Unfold will patch it
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Local apps
    'accounts',
    'core',
    'events',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware', # Add LocaleMiddleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ar'

#default language
DEFAULT_LANGUAGE = 'ar'

LANGUAGES = [
    ('ar', _('Arabic')),
    ('en', _('English')),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'accounts.User'



UNFOLD = {
    "STYLES": [
        lambda request: static("admin/css/style.css"),
    ],
    "SCRIPTS": [
        lambda request: static("admin/js/rtl-fix.js"),
    ],
    "BORDER_RADIUS": "6px",
    "SITE_TITLE": "Hadramout Admin",
    "SITE_HEADER": "Hadramout Admin",
    "INDEX_TITLE": "Dashboard",
    "THEME": "light", 

    # "COLORS": {
    #     "base": {
    #         "50":  "rgb(248,250,252)",              # Slate 50
    #         "100": "rgb(241,245,249)",              # Slate 100
    #         "200": "rgb(226,232,240)",              # Slate 200
    #         "300": "rgb(203,213,225)",              # Slate 300
    #         "400": "rgb(148,163,184)",              # Slate 400
    #         "500": "rgb(100,116,139)",              # Slate 500
    #         "600": "rgb(71,85,105)",                # Slate 600
    #         "700": "rgb(51,65,85)",                 # Slate 700
    #         "800": "rgb(30,41,59)",                 # Slate 800
    #         "900": "rgb(15,23,42)",                 # Slate 900
    #         "950": "rgb(2,6,23)",                   # Slate 950
    #     },

    #     "primary": {
    #         "50":  "rgba(128, 0, 0, 0.10)", # Maroon tint
    #         "100": "rgba(128, 0, 0, 0.20)",
    #         "200": "rgba(128, 0, 0, 0.30)",
    #         "300": "rgba(128, 0, 0, 0.45)",
    #         "400": "rgba(128, 0, 0, 0.65)",
    #         "500": "rgb(128, 0, 0)",        # Maroon Main
    #         "600": "rgb(100, 0, 0)",
    #         "700": "rgb(80, 0, 0)",
    #         "800": "rgb(60, 0, 0)",
    #         "900": "rgb(40, 0, 0)",
    #         "950": "rgb(20, 0, 0)",
    #     },
    # },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": _("Dashboard"),
                "items": [
                    {
                        "title": _("Dashboard"),
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                ],
            },
            {
                "title": _("Accounts"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Users"),
                        "icon": "person",
                        "link": reverse_lazy("admin:accounts_user_changelist"),
                    },
                    {
                        "title": _("Doctors"),
                        "icon": "medical_services",
                        "link": reverse_lazy("admin:accounts_doctor_changelist"),
                    },
                    {
                        "title": _("Vendors"),
                        "icon": "store",
                        "link": reverse_lazy("admin:accounts_vendor_changelist"),
                    },
                ],
            },
            {
                "title": _("Events Management"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Events"),
                        "icon": "event",
                        "link": reverse_lazy("admin:events_event_changelist"),
                    },
                    {
                        "title": _("Vouchers"),
                        "icon": "confirmation_number",
                        "link": reverse_lazy("admin:events_voucher_changelist"),
                    },
                ],
            },
            {
                "title": _("Transactions & Finance"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Transactions"),
                        "icon": "receipt_long",
                        "link": reverse_lazy("admin:core_transaction_changelist"),
                    },
                    {
                        "title": _("Vendor Settlements"),
                        "icon": "account_balance_wallet",
                        "link": reverse_lazy("admin:core_vendorsettlement_changelist"),
                    },
                    {
                        "title": _("Pharma Companies"),
                        "icon": "business",
                        "link": reverse_lazy("admin:core_pharmaceuticalcompany_changelist"),
                    },
                ],
            },
        ],
    },
}

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Static files
STATIC_ROOT = BASE_DIR / 'staticfiles'


# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'hadramoutrestaurant2010@gmail.com'
EMAIL_HOST_PASSWORD = 'doacelvyiwaylxoh'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Auth Redirects
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'
